### ISSUE TITLE
Did you use same scripts for 21.12?

### ISSUE THREAD

**Issue by mohanbayyana** [OracleSiebel/ConfiguringSiebel#117]
Did you use same scripts for 21.12?

**Comment by OracleSiebel** [comment]
Is there a specific issue you're facing?

**Comment by mohanbayyana** [comment]
![image](https://user-images.githubusercontent.com/42014601/147992967-86decacd-3872-4e84-a78e-67606a601d8e.png)

earlier only hostname:port were asking, now changed  include with tlslisterport

**Comment by mohanbayyana** [comment]
bash-4.2# sh -x setGateway -u SADMIN -p ****** -g siebel-pv-18.t-mobile.com -h 9021 -a localhost -b 9011 -t 4330
+ getopts u:p:g:h:a:b:t: option
+ case "${option}" in
+ USER=SADMIN
+ getopts u:p:g:h:a:b:t: option
+ case "${option}" in
+ PASS=********
+ getopts u:p:g:h:a:b:t: option
+ case "${option}" in
+ GATEWAYHOST=siebel-pv-18.t-mobile.com
+ getopts u:p:g:h:a:b:t: option
+ case "${option}" in
+ GATEWAYPORT=9021
+ getopts u:p:g:h:a:b:t: option
+ case "${option}" in
+ SAIHOST=localhost
+ getopts u:p:g:h:a:b:t: option
+ case "${option}" in
+ SAIPORT=9011
+ getopts u:p:g:h:a:b:t: option
+ case "${option}" in
+ TLSLISTNERPORT=4330
+ getopts u:p:g:h:a:b:t: option
+ echo SADMIN
SADMIN
+ echo SADMIN
SADMIN
+ echo siebel-pv-18.t-mobile.com
siebel-pv-18.t-mobile.com
+ echo 9021
9021
+ echo localhost
localhost
+ echo 9011
9011
+ echo 4330
4330
+ '[' -z SADMIN ']'
+ '[' -z SADMIN ']'
+ '[' -z siebel-pv-18.t-mobile.com ']'
+ '[' -z 9021 ']'
+ '[' -z localhost ']'
+ '[' -z 9011 ']'
+ '[' -z 4330 ']'
++ base64
++ echo -n SADMIN:SADMIN
+ ENCODED=U0FETUlOOlNBRE1JTg==
+ JSON='{"CGHostURI":"siebel-pv-18.t-mobile.com:9021"}'
+ echo

+ echo '{"CGHostURI":"siebel-pv-18.t-mobile.com:9021"}'
{"CGHostURI":"siebel-pv-18.t-mobile.com:9021"}
+ echo

+ echo '{"CGHostURI":"siebel-pv-18.t-mobile.com:9021"}'
+ curl -v -k -H 'Content-Length: 46' -H 'Authorization: Basic U0FETUlOOlNBRE1JTg==' -H 'Content-Type: application/json' -X POST https://localhost:9011/siebel/v1.0/cginfo -d @-
* About to connect() to localhost port 9011 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9011 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=*.t-mobile.com
*       start date: Jan 26 00:25:48 2019 GMT
*       expire date: Jan 23 00:25:48 2029 GMT
*       common name: *.t-mobile.com
*       issuer: CN=my-custom-ca
> POST /siebel/v1.0/cginfo HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9011
> Accept: */*
> Content-Length: 46
> Authorization: Basic U0FETUlOOlNBRE1JTg==
> Content-Type: application/json
>
* upload completely sent off: 46 out of 46 bytes
< HTTP/1.1 500 
< Strict-Transport-Security: max-age=31536000;includeSubDomains
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Access-Control-Allow-Origin: *
< Content-Type: text/html;charset=utf-8
< Content-Language: en
< Content-Length: 716
< Date: Tue, 04 Jan 2022 00:01:13 GMT
< Connection: close
<
* Closing connection 0
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Internal Server Error</p><p><b>Description</b> The server encountered an unexpected condition that

**Comment by OracleSiebel** [comment]
This is not a 21.12 change. I think this change came much earlier, though I don't have the actual version number at my fingertips. Certainly it's been this way since MDE, and I uploaded an entire new example build and launch system for that, around 21.2 time. You can see the current version of setGateway supplies the TlsPort:

https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/oraclelinux/classic-mde/manage/scripts/automate-architecture/smc/setGateway#L32

**Comment by mohanbayyana** [comment]
Thanks for quick responce. let me try those scripts

**Comment by mohanbayyana** [comment]
i am still getting same issue
bash-4.2# sh -x setGateway -u SADMIN -p SADMIN -g siebel-pv-18.t-mobile.com -h 9021 -a localhost -b 9011
+ getopts u:p:g:h:a:b: option
+ case "${option}" in
+ USER=SADMIN
+ getopts u:p:g:h:a:b: option
+ case "${option}" in
+ PASS=SADMIN
+ getopts u:p:g:h:a:b: option
+ case "${option}" in
+ GATEWAYHOST=siebel-pv-18.t-mobile.com
+ getopts u:p:g:h:a:b: option
+ case "${option}" in
+ GATEWAYPORT=9021
+ getopts u:p:g:h:a:b: option
+ case "${option}" in
+ SAIHOST=localhost
+ getopts u:p:g:h:a:b: option
+ case "${option}" in
+ SAIPORT=9011
+ getopts u:p:g:h:a:b: option
+ echo SADMIN
SADMIN
+ echo SADMIN
SADMIN
+ echo siebel-pv-18.t-mobile.com
siebel-pv-18.t-mobile.com
+ echo 9021
9021
+ echo localhost
localhost
+ echo 9011
9011
+ '[' -z SADMIN ']'
+ '[' -z SADMIN ']'
+ '[' -z siebel-pv-18.t-mobile.com ']'
+ '[' -z 9021 ']'
+ '[' -z localhost ']'
+ '[' -z 9011 ']'
++ echo -n SADMIN:SADMIN
++ base64
+ ENCODED=U0FETUlOOlNBRE1JTg==
+ JSON='{"CGHostURI":"siebel-pv-18.t-mobile.com:9021","CGTlsPort":"8888"}'
+ echo

+ echo '{"CGHostURI":"siebel-pv-18.t-mobile.com:9021","CGTlsPort":"8888"}'
{"CGHostURI":"siebel-pv-18.t-mobile.com:9021","CGTlsPort":"8888"}
+ echo

+ echo '{"CGHostURI":"siebel-pv-18.t-mobile.com:9021","CGTlsPort":"8888"}'
+ curl -v -k -H 'Content-Length: 65' -H 'Authorization: Basic U0FETUlOOlNBRE1JTg==' -H 'Content-Type: application/json' -X POST https://localhost:9011/siebel/v1.0/cginfo -d @-
* About to connect() to localhost port 9011 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9011 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=*.t-mobile.com
*       start date: Jan 26 00:25:48 2019 GMT
*       expire date: Jan 23 00:25:48 2029 GMT
*       common name: *.t-mobile.com
*       issuer: CN=my-custom-ca
> POST /siebel/v1.0/cginfo HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9011
> Accept: */*
> Content-Length: 65
> Authorization: Basic U0FETUlOOlNBRE1JTg==
> Content-Type: application/json
>
* upload completely sent off: 65 out of 65 bytes
< HTTP/1.1 500 
< Strict-Transport-Security: max-age=31536000;includeSubDomains
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Access-Control-Allow-Origin: *
< Content-Type: text/html;charset=utf-8
< Content-Language: en
< Content-Length: 716
< Date: Tue, 04 Jan 2022 22:40:54 GMT
< Connection: close
<
* Closing connection 0
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Internal Server Error</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><hr class="line" /><h3>Apache Tomcat/9.0.52</h3></body></html>bash-4.2#

**Comment by mohanbayyana** [comment]
05-Jan-2022 00:21:03.406 SEVERE [https-jsse-nio-9011-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [restinbound] in context with path [/siebel] threw exception [java.lang.NullPointerException] with root cause
        java.lang.NullPointerException
                at com.siebel.swsm.config.CloudSourcedConfigReader.postCGHeartBeatWithResponse(CloudSourcedConfigReader.java:1138)
                at com.siebel.integration.eairest.rest.EAI_Resource.putCGInfo(EAI_Resource.java:651)
                at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
                at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)                at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
                at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
                at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
                at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
                at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
                at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
                at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
                at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
                at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
                at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
                at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
                at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
                at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
                at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
                at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
                at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
                at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
                at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
                at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
                at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at com.siebel.integration.eairest.security.RestAuthenticationFilter.doFilterImpl(RestAuthenticationFilter.java:98)
                at com.siebel.integration.eairest.security.RestAuthenticationFilter.doFilter(RestAuthenticationFilter.java:133)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:667)
                at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:289)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)

**Comment by mohanbayyana** [comment]
issue resolved by adding additional resources.

**Comment by OracleSiebel** [comment]
Well done. Thanks for the update!
