### ISSUE TITLE
Networking considerations when deploying on separate hosts

### ISSUE THREAD

**Issue by guoonho** [OracleSiebel/ConfiguringSiebel#134]
What networking considerations are there when each individual container are deployed in separate hosts?

I,e. When trying to deploy each container in separate cloud hosts (where port traffic needs to be explicitly opened) we noticed that the configuration steps stop working along with some SSL errors. This is despite using the same set of SSL certs which work on the ./startAll script method provided in this repo.

SSL errors in CGW container (cloudgateway.log)

```
[ERROR] 2022-06-02 16:21:29.394 [Thread-4] CG_LOGGER - com.siebel.opcgw.cloudgateway.CGSSLCommServer: SSL handshake failed:Remote host terminated the handshake
[ERROR] 2022-06-02 16:21:29.394 [Thread-4] CG_LOGGER - com.siebel.opcgw.cloudgateway.CGSSLCommServer: 
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1470) ~[?:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1298) ~[?:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1199) ~[?:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401) ~[?:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373) ~[?:1.8.0_291]
	at com.siebel.opcgw.cloudgateway.CGSSLCommServer.accept(CGSSLCommServer.java:123) [opcgw.jar:?]
	at com.siebel.opcgw.cloudgateway.CGServer.run(CGServer.java:59) [opcgw.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:480) ~[?:1.8.0_291]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469) ~[?:1.8.0_291]
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:159) ~[?:1.8.0_291]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110) ~[?:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1290) ~[?:1.8.0_291]
	... 6 more
```

Is there any way to figure out who or what the CGW is attempting to establish a SSL connection with? 

In addition, in the Siebel SMC configuration step 3 (Set Up Gateway - Create Registry) this step fails after trying to setup the registry, however I can see that the CGW container is actually now listening to the registry port specified. Any future attempts to configure step 3 will give an error on Registry Port is in use.

```
[ERROR] 2022-06-02 16:30:41.876 [https-jsse-nio-4430-exec-8] CG_LOGGER - com.siebel.opcgw.cloudgateway.config.BootstrapCGResource: Port already in use. Retry with a different registry port
[ERROR] 2022-06-02 16:30:41.876 [https-jsse-nio-4430-exec-8] CG_LOGGER - com.siebel.opcgw.cloudgateway.config.BootstrapCGResource: End: POST on BootstrapCG
```

**Comment by OracleSiebel** [comment]
The simplest way to connect separate Docker instances over multiple machines is to use Docker swarm. This allows the machines to 'see' each other within a Docker network that spans the machines.

**Comment by OracleSiebel** [comment]
Closing due to inactivity. Please re-open if needed.
