### ISSUE TITLE
Invalid Keystore format

### ISSUE THREAD

**Issue by iauroKrunal** [OracleSiebel/ConfiguringSiebel#78]
After running a build from base_siebel (/home/ubuntu/ConfiguringSiebel/Containerization/Docker/ol7/build/base_siebel/build) folder getting following error:

Could you please provide your inputs with regards to following:

```
03-Feb-2020 08:08:10.139 WARNING [main] org.apache.catalina.startup.SetAllPropertiesRule.begin [SetAllPropertiesRule]{Server/Service/Connector} Setting property 'SSLEngine' to 'on' did not find a matching property.
03-Feb-2020 08:08:10.262 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.12
03-Feb-2020 08:08:10.263 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Mar 8 2017 17:41:47 UTC
03-Feb-2020 08:08:10.263 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.12.0
03-Feb-2020 08:08:10.263 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
03-Feb-2020 08:08:10.263 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-1051-aws
03-Feb-2020 08:08:10.263 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
03-Feb-2020 08:08:10.263 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /siebel/sai/jre
03-Feb-2020 08:08:10.263 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_45-b14
03-Feb-2020 08:08:10.263 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
03-Feb-2020 08:08:10.263 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /siebel/sai/applicationcontainer
03-Feb-2020 08:08:10.263 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /siebel/sai/applicationcontainer
03-Feb-2020 08:08:10.264 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/siebel/sai/applicationcontainer/conf/logging.properties
03-Feb-2020 08:08:10.264 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
03-Feb-2020 08:08:10.264 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
03-Feb-2020 08:08:10.264 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
03-Feb-2020 08:08:10.268 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.ssl.trustStore=/siebel/sai/applicationcontainer/siebelcerts/siebelkeystore.jks
03-Feb-2020 08:08:10.269 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.ssl.trustStorePassword=siebel
03-Feb-2020 08:08:10.269 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.ssl.keyStore=/siebel/sai/applicationcontainer/siebelcerts/siebelkeystore.jks
03-Feb-2020 08:08:10.269 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.ssl.keyStorePassword=siebel
03-Feb-2020 08:08:10.269 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/siebel/sai/applicationcontainer
03-Feb-2020 08:08:10.270 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/siebel/sai/applicationcontainer
03-Feb-2020 08:08:10.270 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/siebel/sai/applicationcontainer/temp
03-Feb-2020 08:08:10.271 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
03-Feb-2020 08:08:10.499 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
03-Feb-2020 08:08:10.516 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
03-Feb-2020 08:08:10.519 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["https-jsse-nio-4430"]
03-Feb-2020 08:08:10.741 SEVERE [main] org.apache.coyote.AbstractProtocol.init Failed to initialize end point associated with ProtocolHandler ["https-jsse-nio-4430"]
 java.lang.IllegalArgumentException: java.io.IOException: Invalid keystore format
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:114)
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:85)
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:225)
        at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:972)
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:244)
        at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:558)
        at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:65)
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:968)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
        at org.apache.catalina.core.StandardService.initInternal(StandardService.java:549)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
        at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:875)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)


03-Feb-2020 08:08:10.743 SEVERE [main] org.apache.catalina.core.StandardService.initInternal Failed to initialize connector [Connector[HTTP/1.1-4430]]
 org.apache.catalina.LifecycleException: Failed to initialize component [Connector[HTTP/1.1-4430]]
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:112)
        at org.apache.catalina.core.StandardService.initInternal(StandardService.java:549)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
        at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:875)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:606)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:629)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:311)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:494)
Caused by: org.apache.catalina.LifecycleException: Protocol handler initialization failed
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:970)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
        ... 12 more
Caused by: java.lang.IllegalArgumentException: java.io.IOException: Invalid keystore format
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:114)
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:85)
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:225)
        at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:972)
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:244)
        at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:558)
        at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:65)
```

**Comment by duncanford** [comment]
The key issue seems to be ...

Caused by: java.lang.IllegalArgumentException: java.io.IOException: Invalid keystore format

Could be you missed the process of generating the keystore? Or perhaps used a keystore generated elsewhere?

**Comment by iauroKrunal** [comment]
Thanks for your inputs, but I have ran the following command from manage/SSL folder (/home/ubuntu/ConfiguringSiebel/Containerization/Docker/ol7/manage/SSL/Keys)

```
bash keygen -r .. -s siebel -d *.company.com -c my-custom-ca 2>&1 | tee keygen.log
```

and copied the generated file **siebelkeystore.jks** to /home/ubuntu/ConfiguringSiebel/Containerization/Docker/ol7/build/base_siebel

**Comment by duncanford** [comment]
Are you certain the keygen process ran successfully? You could check the content of your siebelkeystore.jks file with the following command:

keytool -list -v -keystore siebelkeystore.jks -storepass siebel -keypass siebel

That assumes you used the example password defaults.

**Comment by iauroKrunal** [comment]
Yes, when I run the command you mention I'm getting following content

```
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 2 entries

Alias name: ca
Creation date: Feb 4, 2020
Entry type: trustedCertEntry

Owner: CN=my-custom-ca
Issuer: CN=my-custom-ca
Serial number: 4d77a093ebf5c256ccf222bd49b53d047c28f45a
Valid from: Mon Feb 03 16:08:51 UTC 2020 until: Thu Jan 31 16:08:51 UTC 2030
Certificate fingerprints:
	 SHA1: 53:DB:82:45:54:2B:12:E6:7C:85:9C:71:4E:B5:28:E9:6C:8B:0B:22
	 SHA256: 41:36:EF:E2:07:1C:3E:93:1D:11:57:35:69:7C:B3:82:C5:B3:DD:4B:2E:8C:CE:C9:71:9B:CB:8C:20:1A:25:6D
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: E3 7C 6B 98 CD 63 61 CF   87 C5 47 75 D6 FC 14 7B  ..k..ca...Gu....
0010: D1 22 C6 98                                        ."..
]
]

#2: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#3: ObjectId: 2.5.29.15 Criticality=false
KeyUsage [
  Key_CertSign
  Crl_Sign
]

#4: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: E3 7C 6B 98 CD 63 61 CF   87 C5 47 75 D6 FC 14 7B  ..k..ca...Gu....
0010: D1 22 C6 98                                        ."..
]
]



*******************************************
*******************************************


Alias name: siebel
Creation date: Feb 3, 2020
Entry type: PrivateKeyEntry
Certificate chain length: 2
Certificate[1]:
Owner: CN=*.company.com
Issuer: CN=my-custom-ca
Serial number: 1238
Valid from: Mon Feb 03 16:08:51 UTC 2020 until: Thu Jan 31 16:08:51 UTC 2030
Certificate fingerprints:
	 SHA1: 24:BE:BA:99:3E:26:0B:8A:E2:22:E4:74:7F:3D:A6:45:D1:0B:E8:BE
	 SHA256: 50:FB:FD:BE:24:16:E8:E6:12:F4:88:7F:56:89:5F:00:E5:D0:B6:42:0B:0F:A6:88:23:C5:68:D0:15:8C:AD:C2
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: 2.5.29.19 Criticality=false
BasicConstraints:[
  CA:false
  PathLen: undefined
]

#2: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: *.company.com
]

Certificate[2]:
Owner: CN=my-custom-ca
Issuer: CN=my-custom-ca
Serial number: 4d77a093ebf5c256ccf222bd49b53d047c28f45a
Valid from: Mon Feb 03 16:08:51 UTC 2020 until: Thu Jan 31 16:08:51 UTC 2030
Certificate fingerprints:
	 SHA1: 53:DB:82:45:54:2B:12:E6:7C:85:9C:71:4E:B5:28:E9:6C:8B:0B:22
	 SHA256: 41:36:EF:E2:07:1C:3E:93:1D:11:57:35:69:7C:B3:82:C5:B3:DD:4B:2E:8C:CE:C9:71:9B:CB:8C:20:1A:25:6D
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: E3 7C 6B 98 CD 63 61 CF   87 C5 47 75 D6 FC 14 7B  ..k..ca...Gu....
0010: D1 22 C6 98                                        ."..
]
]

#2: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#3: ObjectId: 2.5.29.15 Criticality=false
KeyUsage [
  Key_CertSign
  Crl_Sign
]

#4: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: E3 7C 6B 98 CD 63 61 CF   87 C5 47 75 D6 FC 14 7B  ..k..ca...Gu....
0010: D1 22 C6 98                                        ."..
]
]



*******************************************
*******************************************


```

**Comment by duncanford** [comment]
That does look correct.
Coming back to the error then, where are you seeing this error?

**Comment by iauroKrunal** [comment]
I'm seeing this error, after doing build-all-persistence and running the following command
```
bash startAll 17.0 ent1.sh 
```
from  (/home/ubuntu/ConfiguringSiebel/Containerization/Docker/ol7/manage/scripts/automate-architecture/launch-siebel)  folder 

but when I run the sai image without persistence  and start sai in the lite mode, it works and open the siebel login page
```
    docker run -it -p 443:4430 registry.local.com:5000/siebel/sai:17.0 bash
    cd /siebel/sai/applicationcontainer/bin
    ./startup.sh
```

**Comment by duncanford** [comment]
OK. It's possible that you have your persistence folders in a slightly mangled state. You can't really run properly without persistence. The keystore file is moved from the container to persistence, and so it seems that the file in persistence is there from an earlier attempt where everything didn't go exactly right. Please try the following steps...

1. Stop all Siebel containers.
2. Visit the place where the persistence folders are and completely empty the SAI, SES, and CGW folders.
3. Restart the containers.

Are you obtaining the error from the persistence folders? You still haven't said exactly where (in the filesystem) you are finding the content and I just want to check.

**Comment by iauroKrunal** [comment]
Thanks for your inputs. I will check this in a while. 
As you mentioned in the video, I have created the PV under /var/lib/docker/volumes having ENT1 and under that having SAI, CGW, SES, SFS folders. 

I'm getting the error of "**invalid Keystore format**" in the log situated in the path ( _/siebel/sai/applicationcontainer/ logs/catalina.out_  ) the docker container named **registry.local.com:5000/siebel/sai:17.0**

**Comment by duncanford** [comment]
I'd really recommend you don't waste too much time on 17.0. Upgrade to your target version also.

**Comment by iauroKrunal** [comment]
Okay sure, do you mean the 19.0 version would help to resolve this issue?

**Comment by duncanford** [comment]
Not exactly, I just don't see any value on working hard to resolve issues with the version you're not going to be using. ;)

**Comment by iauroKrunal** [comment]
Sure, thanks a lot. Let me try that as well. Thank you again for all your valuable inputs.
